name: Django CI and Sync

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd meetandgreet
        pip install -r requirements.txt

    - name: Set environment variables
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DEBUG: 'True'
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "DEBUG=True" >> $GITHUB_ENV

    - name: Run Tests
      run: |
        cd meetandgreet  
        python manage.py test

  sync:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Push to deploy repo
      env:
        DEPLOY_REPO_TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git remote add deploy https://${DEPLOY_REPO_TOKEN}@github.com/melixz/nirin_deploy.git
        git push deploy main:main --force
